[env:ee04]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
; XIAO ESP32-S3 Plus: octal PSRAM
board_build.arduino.memory_type = qio_opi
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  zinggjm/GxEPD2@^1.6.9
  tzapu/WiFiManager@^2.0.17
